### ISSUE TITLE
Crash when we open the preferences window

### ISSUE THREAD

**Issue by matrixise** [elboulangero/goodvibes#25]
```
[New Thread 0x7fffe3563700 (LWP 17609)]
[New Thread 0x7fffe2d62700 (LWP 17610)]
[New Thread 0x7fffe0f6a700 (LWP 17611)]

Thread 1 "goodvibes" received signal SIGSEGV, Segmentation fault.
g_object_get_property_uint_bounds (object=object@entry=0x0, property_name=property_name@entry=0x428755 "timeout-seconds", 
    minimum=minimum@entry=0x7fffffffce90, maximum=maximum@entry=0x7fffffffce98) at additions/glib-object.c:119
119		pspec = g_object_class_find_property(G_OBJECT_GET_CLASS(object), property_name);
Missing separate debuginfos, use: dnf debuginfo-install at-spi2-atk-2.22.0-1.fc25.x86_64 at-spi2-core-2.22.0-1.fc25.x86_64 atk-2.22.0-1.fc25.x86_64 bzip2-libs-1.0.6-21.fc25.x86_64 cairo-1.14.8-1.fc25.x86_64 cairo-gobject-1.14.8-1.fc25.x86_64 dbus-libs-1.11.8-1.fc25.x86_64 expat-2.2.0-1.fc25.x86_64 fontconfig-2.12.1-1.fc25.x86_64 freetype-2.6.5-1.fc25.x86_64 gdk-pixbuf2-2.36.3-1.fc25.x86_64 glib2-2.50.2-1.fc25.x86_64 graphite2-1.3.6-1.fc25.x86_64 gstreamer1-1.10.2-1.fc25.x86_64 gstreamer1-plugins-base-1.10.2-1.fc25.x86_64 gtk3-3.22.6-2.fc25.x86_64 gvfs-client-1.30.3-1.fc25.x86_64 harfbuzz-1.3.2-1.fc25.x86_64 ibus-gtk3-1.5.14-5.fc25.x86_64 ibus-libs-1.5.14-5.fc25.x86_64 krb5-libs-1.14.4-4.fc25.x86_64 libX11-1.6.4-3.fc25.x86_64 libXau-1.0.8-6.fc24.x86_64 libXcomposite-0.4.4-8.fc24.x86_64 libXcursor-1.1.14-6.fc24.x86_64 libXdamage-1.1.4-8.fc24.x86_64 libXext-1.3.3-4.fc24.x86_64 libXfixes-5.0.3-1.fc25.x86_64 libXi-1.7.8-2.fc25.x86_64 libXinerama-1.1.3-6.fc24.x86_64 libXrandr-1.5.1-1.fc25.x86_64 libXrender-0.9.10-1.fc25.x86_64 libXxf86vm-1.1.4-3.fc24.x86_64 libblkid-2.28.2-1.fc25.x86_64 libcap-2.25-2.fc25.x86_64 libcom_err-1.43.3-1.fc25.x86_64 libdatrie-0.2.9-3.fc25.x86_64 libdrm-2.4.74-1.fc25.x86_64 libepoxy-1.3.1-3.fc25.x86_64 libgcc-6.3.1-1.fc25.x86_64 libgcrypt-1.6.6-1.fc25.x86_64 libgpg-error-1.24-1.fc25.x86_64 libmount-2.28.2-1.fc25.x86_64 libpng-1.6.27-1.fc25.x86_64 libselinux-2.5-13.fc25.x86_64 libsoup-2.56.0-2.fc25.x86_64 libthai-0.1.25-1.fc25.x86_64 libuuid-2.28.2-1.fc25.x86_64 libwayland-client-1.12.0-1.fc25.x86_64 libwayland-cursor-1.12.0-1.fc25.x86_64 libwayland-server-1.12.0-1.fc25.x86_64 libxcb-1.12-1.fc25.x86_64 libxkbcommon-0.6.1-1.fc25.x86_64 libxml2-2.9.3-4.fc25.x86_64 libxshmfence-1.2-3.fc24.x86_64 lz4-1.7.5-1.fc25.x86_64 mesa-libEGL-13.0.3-1.fc25.x86_64 mesa-libGL-13.0.3-1.fc25.x86_64 mesa-libgbm-13.0.3-1.fc25.x86_64 mesa-libglapi-13.0.3-1.fc25.x86_64 mesa-libwayland-egl-13.0.3-1.fc25.x86_64 orc-0.4.26-1.fc25.x86_64 pango-1.40.3-1.fc25.x86_64 pcre-8.40-1.fc25.x86_64 pixman-0.34.0-2.fc24.x86_64 sqlite-libs-3.14.2-1.fc25.x86_64 systemd-libs-231-12.fc25.x86_64
(gdb) bt
#0  0x000000000040ace6 in g_object_get_property_uint_bounds (object=object@entry=0x0, property_name=property_name@entry=0x428755 "timeout-seconds", minimum=minimum@entry=0x7fffffffce90, maximum=maximum@entry=0x7fffffffce98) at additions/glib-object.c:119
#1  0x0000000000416616 in setup_adjustment (obj_prop=0x428755 "timeout-seconds", obj=0x0, adjustment=0x7eaf60) at ui/gv-prefs-window.c:198
#2  0x0000000000416616 in gv_prefs_window_setup_widgets (self=0xb9eaa0) at ui/gv-prefs-window.c:381
#3  0x0000000000416616 in gv_prefs_window_constructed (object=0xb9eaa0) at ui/gv-prefs-window.c:520
#4  0x00007ffff6881c17 in g_object_new_internal () at /lib64/libgobject-2.0.so.0
#5  0x00007ffff68830ad in g_object_newv () at /lib64/libgobject-2.0.so.0
#6  0x00007ffff6883864 in g_object_new () at /lib64/libgobject-2.0.so.0
#7  0x0000000000416b29 in gv_prefs_window_new () at ui/gv-prefs-window.c:276
#8  0x0000000000419685 in gv_ui_present_preferences () at ui/gv-ui.c:68
#9  0x00007ffff687c3e5 in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#10 0x00007ffff688e432 in signal_emit_unlocked_R () at /lib64/libgobject-2.0.so.0
#11 0x00007ffff689705f in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#12 0x00007ffff689743f in g_signal_emit () at /lib64/libgobject-2.0.so.0
#13 0x00007ffff6e77b55 in g_simple_action_activate () at /lib64/libgio-2.0.so.0
#14 0x00007ffff5853ace in gtk_action_muxer_activate_action () at /lib64/libgtk-3.so.0
#15 0x00007ffff5853b04 in gtk_action_muxer_activate_action () at /lib64/libgtk-3.so.0
#16 0x00007ffff5853b04 in gtk_action_muxer_activate_action () at /lib64/libgtk-3.so.0
#17 0x00007ffff59aca06 in gtk_menu_tracker_item_activated () at /lib64/libgtk-3.so.0
#18 0x00007ffff687c3e5 in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#19 0x00007ffff688e432 in signal_emit_unlocked_R () at /lib64/libgobject-2.0.so.0
#20 0x00007ffff689705f in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#21 0x00007ffff689743f in g_signal_emit () at /lib64/libgobject-2.0.so.0
#22 0x00007ffff5adb50e in gtk_widget_activate () at /lib64/libgtk-3.so.0
#23 0x00007ffff59a9326 in gtk_menu_shell_activate_item () at /lib64/libgtk-3.so.0
#24 0x00007ffff59a965b in gtk_menu_shell_button_release () at /lib64/libgtk-3.so.0
#25 0x00007ffff598c5e1 in _gtk_marshal_BOOLEAN__BOXEDv () at /lib64/libgtk-3.so.0
#26 0x00007ffff687c614 in _g_closure_invoke_va () at /lib64/libgobject-2.0.so.0
#27 0x00007ffff68968b3 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#28 0x00007ffff689743f in g_signal_emit () at /lib64/libgobject-2.0.so.0
#29 0x00007ffff5ad901c in gtk_widget_event_internal () at /lib64/libgtk-3.so.0
#30 0x00007ffff59895ee in propagate_event () at /lib64/libgtk-3.so.0
#31 0x00007ffff598b62e in gtk_main_do_event () at /lib64/libgtk-3.so.0
#32 0x00007ffff73c0515 in _gdk_event_emit () at /lib64/libgdk-3.so.0
#33 0x00007ffff73f1532 in gdk_event_source_dispatch () at /lib64/libgdk-3.so.0
#34 0x00007ffff6b08e42 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#35 0x00007ffff6b091c0 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#36 0x00007ffff6b0926c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#37 0x00007ffff6e6fbbd in g_application_run () at /lib64/libgio-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#38 0x000000000040a6a0 in main (argc=<optimized out>, argv=<optimized out>) at main.c:202
(gdb) 
```

**Comment by elboulangero** [comment]
Hi matrixise,

Ijust fixed that in the latest commit (I was working on that at the very moment, you couldn't be more on time). Please pull the last changes, be sure to clean (as it impacts the build system), rebuild. Please confirm that the problem is fixed.

Cheers !

**Comment by matrixise** [comment]
Thank you, I am going to check

**Comment by elboulangero** [comment]
If you installed from the [PPA on Launchpad](https://launchpad.net/~elboulangero/+archive/ubuntu/goodvibes), just upgrade your system and it will work nice and clean.
